---
title: "2022_06_06_ChIRP_PeptideAnalysis"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(rstatix)
library(ggpubr)
library(dplyr)
library(purrr)
library(janitor)
library(ggplot2)
library(ggvenn)
library(VennDiagram)
library(venneuler)
library(eulerr)
library(reshape)
library(DiagrammeR)
library(ggrepel)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Import and Clean up Data

#Mar2022 Kit Data for Peptides
mass_spec_50ng_peptide_Mar2022_TV <- read_csv("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP/2022_03_24data_50ng_peptide_Mar2022ChIRPOandE.csv") %>% clean_names()
mass_spec_100ng_peptide_Mar2022_TV <- read_csv("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP/2022_03_24data_100ng_peptide_Mar2022ChIRPOandE.csv") %>% clean_names()

#Combine the gene name with the peptide sequence
mass_spec_50ng_peptide_Mar2022_TV$peptide_name <- paste(mass_spec_50ng_peptide_Mar2022_TV$gene, mass_spec_50ng_peptide_Mar2022_TV$peptide_sequence, sep="_")

mass_spec_100ng_peptide_Mar2022_TV$peptide_name <- paste(mass_spec_100ng_peptide_Mar2022_TV$gene, mass_spec_100ng_peptide_Mar2022_TV$peptide_sequence, sep="_")

#Intensities only data
Intensities_50ng_peptide <- mass_spec_50ng_peptide_Mar2022_TV[,c(33,21,22,23,24,25)]
colnames(Intensities_50ng_peptide)[2:6] <- paste(colnames(Intensities_50ng_peptide)[2:6],"50ng",sep=".")

Intensities_100ng_peptide <- mass_spec_100ng_peptide_Mar2022_TV[,c(33,21,22,23,24,25)]
colnames(Intensities_100ng_peptide)[2:6] <- paste(colnames(Intensities_100ng_peptide)[2:6],"100ng",sep=".")

Intensities <- full_join(Intensities_50ng_peptide,Intensities_100ng_peptide,by="peptide_name",copy=FALSE,keep = FALSE)
Intensities <- as.data.frame(Intensities)

#From the fulljoin, I need to change NA's to Zeros
Intensities <- Intensities %>% replace_na(list(r2_ko_oe_intensity.50ng = 0.0, r2_wt_oe_intensity.50ng = 0.0, r3_ko_oe_intensity.50ng = 0.0, r3_wt_oe_intensity.50ng = 0.0, r4_wt_oe_intensity.50ng=0.0, r2_ko_oe_intensity.100ng=0.0, r2_wt_oe_intensity.100ng=0.0, r3_wt_oe_intensity.100ng=0.0, r3_ko_oe_intensity.100ng=0.0, r4_wt_oe_intensity.100ng=0.0))

#Took out the input only peptides
Intensities_inputcleared <- Intensities[rowSums(Intensities > 0) >= 2,]

#Calculated fold enrichment for all
Intensities_inputcleared$wt_mean <- rowMeans(subset( Intensities_inputcleared, select = c(r2_wt_oe_intensity.50ng, r3_wt_oe_intensity.50ng, r4_wt_oe_intensity.50ng, r2_wt_oe_intensity.100ng, r3_wt_oe_intensity.100ng, r4_wt_oe_intensity.100ng)),)
Intensities_inputcleared$ko_mean <- rowMeans(subset(Intensities_inputcleared, select = c(r2_ko_oe_intensity.50ng, r3_ko_oe_intensity.50ng, r2_ko_oe_intensity.100ng, r3_ko_oe_intensity.100ng)),)
Intensities_inputcleared_nonzero <- Intensities_inputcleared %>% map_if(is.numeric, ~.+1)
Intensities_inputcleared_nonzero <- as.data.frame(Intensities_inputcleared_nonzero)
Intensities_inputcleared_nonzero <- Intensities_inputcleared_nonzero %>% mutate(ratio = wt_mean/ko_mean)
Intensities_inputcleared_nonzero$logratio = log(Intensities_inputcleared_nonzero$ratio,10)


#Calculated wilcoxon and t-test values for all
Intensities_inputcleared_nonzero$ttest_pvalue <- sapply(1:nrow(Intensities_inputcleared_nonzero), function(i) t.test(as.numeric(as.character(unlist(Intensities_inputcleared_nonzero[i,c(2,4,7,9)]))), as.numeric(as.character(unlist(Intensities_inputcleared_nonzero[i,c(3,5,6,8,10,11)]))))[c("p.value")])
Intensities_inputcleared_nonzero$ttest_pvalue <- as.numeric(unlist(Intensities_inputcleared_nonzero$ttest_pvalue))

Intensities_inputcleared_nonzero$wilcoxtest_pvalue <- sapply(1:nrow(Intensities_inputcleared_nonzero), function(i) wilcox.test(as.numeric(as.character(unlist(Intensities_inputcleared_nonzero[i,c(2,4,7,9)]))), as.numeric(as.character(unlist(Intensities_inputcleared_nonzero[i,c(3,5,6,8,10,11)]))))[c("p.value")])
Intensities_inputcleared_nonzero$wilcoxtest_pvalue <- as.numeric(unlist(Intensities_inputcleared_nonzero$wilcoxtest_pvalue))


#Made graphs of all before I do any filtering to compare with the protein data
pdf("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP//2022_06_06_Histogram_beforefilter_peptide_FoldChange_WT_KO_MassSpec_Mar2022TV.pdf")
hist(Intensities_inputcleared_nonzero$logratio, breaks = 50, main="Frequency of Log Average of Fold Change of WT/KO Intensities \nfrom TVkitMar2022 peptides", xlab = "Log Average Fold Change of WT to KO of all peptides (no filter)", ylab = "Frequency of Peptides (n=2134)", labels=TRUE) 
dev.off()

pdf("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP//2022_06_06_Histogram_beforefilter_peptide_Ttest_WT_KO_MassSpec_Mar2022TV.pdf")
hist(Intensities_inputcleared_nonzero$ttest_pvalue, breaks = 20, main=" Frequency of T-Test P-values in Mar2022 ChIRP Peptide Data (No Filter)", xlab = "T-Test P-value", ylab = "Frequency of P-values", labels=TRUE) 
dev.off()

pdf("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP//2022_06_06_Histogram_beforefilter_peptide_Wilcoxontest_WT_KO_MassSpec_Mar2022TV.pdf")
hist(Intensities_inputcleared_nonzero$wilcoxtest_pvalue, breaks = 20, main="Frequency of Wilcoxon P-values in Mar2022 ChIRP Peptide Data (No Filter)", xlab = "Wilcoxon P-value", ylab = "Frequency of P-values", labels=TRUE) 
dev.off()

```


#Now going to go through the pipeline to see what comes out
```{r}
#WT and KO Checks
Intensities_inputcleared_nonzero$wt_check <- rowSums(Intensities_inputcleared_nonzero[,c(3,5,6,8,10,11)] >1)
Intensities_inputcleared_nonzero$ko_check <- rowSums(Intensities_inputcleared_nonzero[,c(2,4,7,9)] >1)

#Filter 4 out of 6 WT
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck <- dplyr::filter(Intensities_inputcleared_nonzero, wt_check >= 4)
#after 4 out of 6 wt, 430 peptides

#Filter 1.5 ratio
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck <- dplyr::filter(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck, ratio >= 1.5)
#by itself there are 1041 peptides above 1.5 ratio
#but with the 4 out of 6 ratio previously applied, n=82

#Filter 1 out of 4 KO
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck <- dplyr::filter(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck, ko_check <= 1)
#after 1 or less KO, n=41
#without the ratio filter but with 4 out of 5, n=42

#Filter 0 out of 4 KO
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_0kocheck <- dplyr::filter(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck, ko_check <= 0)
#no ko, n=19

#Write 1 out of 4 KO to CSV to do a nuclear check
write.csv(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck,"/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP//2022_06_07_results_4outof6_wtcheck_1.5filtercutoff_1kocutoff.csv",row.names = TRUE)

#Make BoxWhisker of all 42 Genes
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready <- as.data.frame(t(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck))
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2 <- Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready[1:11,]
Intensities_peptide_newcol <- c("genotype","KO","WT","KO","WT","WT","KO","WT","KO","WT","WT")
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2 <- cbind(Intensities_peptide_newcol,Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2)
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2<-Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2 %>% row_to_names (row_number= 1) %>% clean_names()
Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2[] <- lapply(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2, type.convert, as.is = TRUE)
melted_Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2 = melt(Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2)

for (var in melted_Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2$variable) { 
 
  pdf(paste("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP/2022_06_06_BoxWhiskerPlots_max1ko_peptide//", var, "peptide_4outof6wtcheck_ratiocutoff_1komax.pdf", sep=""))
  print(ggboxplot(melted_Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2[melted_Intensities_inputcleared_nonzero_4_out_of_6_wtcheck_ratiocheck_1kocheck_ready2$variable==var,],x="genotype",y="value",fill="#00AFBB",line.color ="gray",add="jitter")+ggtitle(var)+stat_compare_means(label.x = 0.5)+stat_compare_means(method = "t.test"))
 dev.off()
  }






```

#Reverse Analysis for KO because we want to make sure we have some good hits. 
```{r}
#Filter 3 out of 4 KO
Intensities_inputcleared_nonzero_revKO <- dplyr::filter(Intensities_inputcleared_nonzero, ko_check >= 3)
#after 3 out of 4 ko, 534 peptides

#Filter ratio 1/1.5 = 0.667
Intensities_inputcleared_nonzero_revKO_ratiocheck <- dplyr::filter(Intensities_inputcleared_nonzero_revKO, ratio <= 0.667)
#with the 3 out of 4ko and revKO ratio, n=310

#Filter 1 out of 6 WT
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck <- dplyr::filter(Intensities_inputcleared_nonzero_revKO_ratiocheck, wt_check <= 1)
#n=84

#Write 1 out of 4 KO to CSV to do a nuclear check
write.csv(Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck,"/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP//2022_06_07_RevKO_analysis_results.csv",row.names = TRUE)

#Make BoxWhisker of all 42 Genes
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready <- as.data.frame(t(Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck))
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2 <- Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready[1:11,]
Intensities_peptide_newcol <- c("genotype","KO","WT","KO","WT","WT","KO","WT","KO","WT","WT")
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2 <- cbind(Intensities_peptide_newcol,Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2)
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2<-Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2 %>% row_to_names (row_number= 1) %>% clean_names()
Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2[] <- lapply(Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2, type.convert, as.is = TRUE)
melted_Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2 = melt(Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2)

for (var in melted_Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2$variable) { 
 
  pdf(paste("/scratch/Shares/rinn/tenaya/ChChCh/2022_06_06_Peptide_MarChIRP/2022_06_06_RevKO_BoxWhiskerPlots_peptide//", var, "RevKO_peptide.pdf", sep=""))
  print(ggboxplot(melted_Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2[melted_Intensities_inputcleared_nonzero_revKO_ratiocheck_wtcheck_ready2$variable==var,],x="genotype",y="value",fill="#00AFBB",line.color ="gray",add="jitter")+ggtitle(var)+stat_compare_means(label.x = 0.5)+stat_compare_means(method = "t.test"))
 dev.off()
  }

```

